export const stateCode = {
    'Itaim I-SP': 'https://allpfit.com.br/checkout-itaim/',
    'Itaim II-SP': 'https://allpfit.com.br/checkout-itaim-ii/',
    'Aricanduva-SP': 'https://allpfit.com.br/checkout-aricanduva/',
    'Vila Carrão-SP': 'https://allpfit.com.br/checkout-carrao/',
    'Coronel Fabriciano-MG': 'https://allpfit.com.br/checkout-coronel-fabriciano/',
    'Ferraz de Vasconcelos-SP': 'https://allpfit.com.br/checkout-ferraz/',
    'Grajaú-SP': 'https://allpfit.com.br/checkout-grajau/',
    'Ipatinga-MG': 'https://allpfit.com.br/checkout-ipatinga-cidade-nobre/',
    'Itabuna-BA': 'https://allpfit.com.br/checkout-itabuna/',
    'Londrina-PR': 'https://allpfit.com.br/pre-venda-londrina-pr/',
    'Mogi das Cruzes-SP': 'https://allpfit.com.br/checkout-mogi-das-cruzes/',
    'Poá-SP': 'https://allpfit.com.br/checkout-poa/',
    'Porto Alegre-RS': 'https://allpfit.com.br/checkout-porto-alegre/',
    'Praia Grande-SP': 'https://allpfit.com.br/checkout-praia-grande/',
    'Santana de Parnaíba-SP': 'https://allpfit.com.br/checkout-santana-de-pnb/',
    'São Caetado do Sul-SP': 'https://allpfit.com.br/checkout-sao-caetano/',
    'Shopping Vale do Aço': 'https://allpfit.com.br/checkout-ipatinga-shopping-do-vale/',
    'São José do Rio Preto-SP': 'https://allpfit.com.br/checkout-sjrp/',
    'Suzano-SP': 'https://allpfit.com.br/checkout-suzano/',
    'Viamão-RS': 'https://allpfit.com.br/checkout-viamao/',
    'Vila Sônia-SP': 'https://allpfit.com.br/checkout-vila-sonia/',
    'Vitória da Conquista-BA': 'https://allpfit.com.br/checkout-vitoria-da-conquista/',
    'Sorocaba - SP': 'https://allpfit.com.br/checkout-sorocaba/',
    'Vila Guarani-SP':'https://allpfit.com.br/checkout-sorocaba/',
    'Santo Amaro-SP': 'https://allpfit.com.br/checkout-sorocaba/' 
};